import os
import datetime
from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build

# If modifying these SCOPES, delete the file token.json.
SCOPES = ['https://www.googleapis.com/auth/calendar']

def get_calendar_service():
    creds = None
    # The file token.json stores the user's access and refresh tokens.
    # It is created automatically when the authorization flow completes for the first time.
    token_path = os.path.join(os.path.dirname(__file__), 'token.json')
    
    if os.path.exists(token_path):
        creds = Credentials.from_authorized_user_file(token_path, SCOPES)
    
    # If there are no (valid) credentials available, let the user log in.
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            # Note: This part requires a browser. Run it locally once to generate token.json
            cred_path = os.path.join(os.path.dirname(__file__), 'credentials.json')
            flow = InstalledAppFlow.from_client_secrets_file(cred_path, SCOPES)
            creds = flow.run_local_server(port=0)
        
        # Save the credentials for the next run
        with open(token_path, 'w') as token:
            token.write(creds.to_json())

    return build('calendar', 'v3', credentials=creds)

def add_event_to_calendar(doctor_name, doctor_email, patient_name, patient_email, start_time_str):
    try:
        service = get_calendar_service()

        # Convert ISO string to datetime object to calculate end time
        # Format example: '2023-10-28T09:00:00'
        start_dt = datetime.datetime.fromisoformat(start_time_str)
        
        # Adding 30 minutes for a standard medical slot
        end_dt = start_dt + datetime.timedelta(minutes=30)
        
        event = {
            'summary': f'Appointment with Dr. {doctor_name}',
            'description': f'Patient: {patient_name}. Generated by HMS System.',
            'start': {
                'dateTime': start_dt.isoformat(),
                'timeZone': 'UTC',
            },
            'end': {
                'dateTime': end_dt.isoformat(),
                'timeZone': 'UTC',
            },
            'attendees': [
                {'email': doctor_email},
                {'email': patient_email},
            ],
            'reminders': {
                'useDefault': False,
                'overrides': [
                    {'method': 'email', 'minutes': 24 * 60},
                    {'method': 'popup', 'minutes': 10},
                ],
            },
        }

        event = service.events().insert(calendarId='primary', body=event, sendUpdates='all').execute()
        return event.get('htmlLink')

    except Exception as e:
        print(f"An error occurred: {e}")
        return None
